version: '2.4'
services:
  crew_app:
    build: ./
    container_name: crew_container
    restart: always
    ports:
      - '5000:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://crew_app:5000']
      interval: 10s
      timeout: 60s
      retries: 5

  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      crew_app:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://crew_app:5000
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
